# Generated by Django 5.2.5 on 2025-08-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('enrollment_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('attended', models.IntegerField()),
                ('conducted', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('mentor', models.CharField(max_length=50)),
                ('s_score', models.FloatField()),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
