# Generated by Django 5.1.5 on 2025-08-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classschedule_student_reason_for_low_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='class_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
